import pandas as pd

#
#  COUNTRIES
#

country_names = ['',
    'afghanistan','aland islands','albania','algeria','american samoa',
    'andorra','angola','anguilla','antarctica','antigua and barbuda',
    'argentina','armenia','aruba','australia','austria',
    'azerbaijan','bahamas','bahrain','bangladesh','barbados',
    'belarus','belgium','belize','benin','bermuda',
    'bhutan','bolivia','bonaire','bosnia and herzegovina','botswana',
    'bouvet island','brazil','british indian ocean territory','brunei','bulgaria',
    'burkina faso','burundi','cambodia','cameroon','canada',
    'cape verde','cayman islands','central african republic','chad','chile',
    'china','christmas island','cocos islands','colombia','comoros',
    'cook islands','costa rica',"cote d'ivoire",'croatia','cuba',
    'curacao','cyprus','czech republic','democratic congo','denmark',
    'djibouti','dominica','dominican republic','east timor','ecuador',
    'egypt','el salvador','england','equatorial guinea','eritrea',
    'estonia','ethiopia','european union','falkland islands',
    'faroe islands','fiji','finland','france','french guiana','french polynesia',
    'french southern territories','gabon','gambia','georgia','germany',
    'ghana','gibraltar','greece','greenland','grenada',
    'guadeloupe','guam','guatemala','guernsey','guinea',
    'guinea-bissau','guyana','haiti','heard island and mcdonald islands','honduras',
    'hong kong','hungary','iceland','india','indonesia',
    'iran','iraq','ireland','isle of man','israel',
    'italy','jamaica','japan','jersey','jordan',
    'kazakhstan','kenya','kiribati','north korea','south korea',
    'kosovo','kuwait','kyrgyzstan','laos','latvia',
    'lebanon','lesotho','liberia','libya','liechtenstein',
    'lithuania','luxembourg','macau','macedonia','madagascar',
    'malawi','malaysia','maldives','mali','malta',
    'marshall islands','martinique','mauritania','mauritius','mayotte',
    'mexico','micronesia','moldova','monaco','mongolia',
    'montenegro','montserrat','morocco','mozambique','myanmar',
    'namibia','nauru','nepal','netherlands','new caledonia',
    'new zealand','nicaragua','niger','nigeria','niue',
    'norfolk island','northern mariana islands','norway','oman','pakistan',
    'palau','palestine','panama','papua new guinea','paraguay',
    'peru','philippines','pitcairn islands','poland','portugal',
    'puerto rico','qatar','congo','reunion','romania',
    'russia','rwanda','saint barthelemy','saint helena','saint kitts and nevis',
    'saint lucia','saint martin','saint pierre and miquelon','saint vincent and the grenadines','samoa',
    'san marino','sao tome and principe','saudi arabia','scotland','senegal',
    'serbia','seychelles','sierra leone','singapore','sint maarten',
    'slovakia','slovenia','solomon islands','somalia','south africa',
    'south georgia and the south sandwich islands','south sudan','spain','sri lanka','sudan',
    'suriname','svalbard and jan mayen','swaziland','sweden','switzerland',
    'syria','taiwan','tajikistan','tanzania','thailand',
    'togo','tokelau','tonga','trinidad and tobago','tunisia','turkey',
    'turkmenistan','turks and caicos islands','tuvalu','uganda','ukraine',
    'dubai', 'united arab emirates',
    'united kingdom','united states','uruguay',
    'ussr','uzbekistan','vanuatu','vatican city','venezuela',
    'vietnam','virgin islands british','virgin islands us','wales','wallis and futuna',
    'western sahara','yemen','zambia','zimbabwe','zz country', ''
]

# https://pt.wikipedia.org/wiki/ISO_3166-1_alfa-3
country_isoa3 = ['',
    'AFG', 'ALA', 'ALB', 'DZA', 'ASM', 'AND', 'AGO', 'AIA', 'ATA', 'ATG',
    'ARG', 'ARM', 'ABW', 'AUS', 'AUT', 'AZE', 'BHS', 'BHR', 'BGD', 'BRB',
    'BLR', 'BEL', 'BLZ', 'BEN', 'BMU', 'BTN', 'BOL', 'BES', 'BIH', 'BWA',
    'BVT', 'BRA', 'IOT', 'BRN', 'BGR', 'BFA', 'BDI', 'KHM', 'CMR', 'CAN',
    'CPV', 'CYM', 'CAF', 'TCD', 'CHL', 'CHN', 'CXR', 'CCK', 'COL', 'COM',
    'COK', 'CRI', 'CIV', 'HRV', 'CUB', 'CUW', 'CYP', 'CZE', 'COD', 'DNK',
    'DJI', 'DMA', 'DOM', 'TLS', 'ECU', 'EGY', 'SLV', 'ENG', 'GNQ', 'ERI',
    'EST', 'ETH', 'EUR', 'FLK', 'FRO', 'FJI', 'FIN', 'FRA', 'GUF', 'PYF',
    'ATF', 'GAB', 'GMB', 'GEO', 'DEU', 'GHA', 'GIB', 'GRC', 'GRL', 'GRD',
    'GLP', 'GUM', 'GTM', 'GGY', 'GIN', 'GNB', 'GUY', 'HTI', 'HMD', 'HND',
    'HKG', 'HUN', 'ISL', 'IND', 'IDN', 'IRN', 'IRQ', 'IRL', 'IMN', 'ISR',
    'ITA', 'JAM', 'JPN', 'JEY', 'JOR', 'KAZ', 'KEN', 'KIR', 'PRK', 'KOR',
    'XKX', 'KWT', 'KGZ', 'LAO', 'LVA', 'LBN', 'LSO', 'LBR', 'LBY', 'LIE',
    'LTU', 'LUX', 'MAC', 'MKD', 'MDG', 'MWI', 'MYS', 'MDV', 'MLI', 'MLT',
    'MHL', 'MTQ', 'MRT', 'MUS', 'MYT', 'MEX', 'FSM', 'MDA', 'MCO', 'MNG',
    'MNE', 'MSR', 'MAR', 'MOZ', 'MMR', 'NAM', 'NRU', 'NPL', 'NLD', 'NCL',
    'NZL', 'NIC', 'NER', 'NGA', 'NIU', 'NFK', 'MNP', 'NOR', 'OMN', 'PAK',
    'PLW', 'PSE', 'PAN', 'PNG', 'PRY', 'PER', 'PHL', 'PCN', 'POL', 'PRT',
    'PRI', 'QAT', 'COG', 'REU', 'ROU', 'RUS', 'RWA', 'BLM', 'SHN', 'KNA',
    'LCA', 'MAF', 'SPM', 'VCT', 'WSM', 'SMR', 'STP', 'SAU', 'SCT', 'SEN',
    'SRB', 'SYC', 'SLE', 'SGP', 'SXM', 'SVK', 'SVN', 'SLB', 'SOM', 'ZAF',
    'SGS', 'SSD', 'ESP', 'LKA', 'SDN', 'SUR', 'SJM', 'SWZ', 'SWE', 'CHE',
    'SYR', 'TWN', 'TJK', 'TZA', 'THA', 'TGO', 'TKL', 'TON', 'TTO', 'TUN',
    'TUR', 'TKM', 'TCA', 'TUV', 'UGA', 'UKR', 'ARE', 'ARE', 'GBR', 'USA', 'URY',
    'SUN', 'UZB', 'VUT', 'VAT', 'VEN', 'VNM', 'VGB', 'VIR', 'WLS', 'WLF',
    'ESH', 'YEM', 'ZMB', 'ZWE', 'WWW', ''
]

idx_country_names_pt = [
    'Venezuela',
    'Brasil',
    'Hong Kong',
    'Malta',
    'Malásia',
    'Nova<br>Zelândia',
    'Colômbia',
    'Peru',
    'Coréia<br>do Sul',
    'Japão',
    'Paquistão',
    'Tanzânia',
    'Montenegro',
    'Tunísia',
    'Filipinas',
    'China',
    'Espanha',
    'Egito',
    'Cingapura',
    'Chile',
    'Nigéria',
    'Grécia',
    'Quênia',
    'Sérvia',
    'Tailândia',
    'Uganda',
    'Reino Unido',
    'Indonésia',
    'Iraque',
    'Alemanha',
    'Austrália',
    'Polônia',
    'Portugal',
    'Omã',
    'EUA<br>Dow 30',
    'México',
    'Qatar',
    'Finlândia',
    'Bélgica',
    'Suiça',
    'Croácia',
    'Eslováquia',
    'Marrocos',
    'Bahren',
    'Itália',
    'África<br>do Sul',
    'Dinamarca',
    'Rússia',
    'Taiwan',
    'Canadá',
    'Suécia',
    'EUA<br>NASDAQ',
    'França',
    'Índia',
    # 'Kuwait',
    'Hungria',
    'Turquia',
    'Dubai',  # 'Emirados<br>Árabes Unidos',
    'Arábia<br>Saudita',
    'Noruega',
    'Israel',
    'Romênia',
    'Holanda',
    'Bangladesh',
    'Jordânia',
    'Áustria',
    'Islândia',
    'Eslovênia',
    'República<br>Tcheca',
    'Cazaquistão',
    'Zâmbia',
    'Bulgária',
    'Vietnã',
    'Líbano',
    'Costa Rica',
    'Argentina',
    'Sri Lanka',
    'Mongólia',
    # 'Zimbábue',
]

idx_country_names = [
    'Venezuela',
    'Brazil',
    'Hong Kong',
    'Malta',
    'Malaysia',
    'New Zealand',
    'Colombia',
    'Peru',
    'South Korea',
    'Japan',
    'Pakistan',
    'Tanzania',
    'Montenegro',
    'Tunisia',
    'Philippines',
    'China',
    'Spain',
    'Egypt',
    'Singapore',
    'Chile',
    'Nigeria',
    'Greece',
    'Kenya',
    'Serbia',
    'Thailand',
    'Uganda',
    'United Kingdom',
    'Indonesia',
    'Iraq',
    'Germany',
    'Australia',
    'Poland',
    'Portugal',
    'Oman',
    'United States',
    'Mexico',
    'Qatar',
    'Finland',
    'Belgium',
    'Switzerland',
    'Croatia',
    'Slovakia',
    'Morocco',
    'Bahrain',
    'Italy',
    'South Africa',
    'Denmark',
    'Russia',
    'Taiwan',
    'Canada',
    'Sweden',
    'United States 2',
    'France',
    'India',
    # 'Kuwait',
    'Hungary',
    'Turkey',
    'Dubai',  # 'United Arab Emirates',
    'Saudi Arabia',
    'Norway',
    'Israel',
    'Romania',
    'Netherlands',
    'Bangladesh',
    'Jordan',
    'Austria',
    'Iceland',
    'Slovenia',
    'Czech Republic',
    'Kazakhstan',
    'Zambia',
    'Bulgaria',
    'Vietnam',
    'Lebanon',
    'Costa Rica',
    'Argentina',
    'Sri Lanka',
    'Mongolia',
    # 'Zimbabwe',
]

idx_names = [
    'Bursatil',
    'Bovespa',
    'Hang Seng',
    'MSE',
    'KLCI',
    'NZX ALL',
    'FTSE Colombia',
    'S&P Lima General',
    'KOSPI',
    'NIKKEI 225',
    'KMI All Shares',
    'Tanzania All Share',
    'MONEX',
    'TUNINDEX',
    'FTSE Philippines',
    'Shanghai',
    'IBEX 35',
    'EGX 30',
    'FTSE Singapore',
    'S&P CLX IPSA',
    'NSE All Share',
    'FTSE/Athex 20',
    'Nairobi All Share',
    'BELEX 15',
    'SET',
    'Uganda All Share',
    'FTSE 100',
    'IDX Composite',
    'ISX Main 60',
    'DAX',
    'S&P/ASX 200',
    'WIG20',
    'PSI 20',
    'MSM 30',
    'Dow 30',
    'S&P/BMV IPC',
    'QE All Shares',
    'OMX Helsinki',
    'BEL 20',
    'SMI',
    'CROBEX',
    'SAX',
    'Moroccan All Shares',
    'Bahrain All Share',
    'FTSE MIB',
    'FTSE/JSE Top 40',
    'OMX Copenhagen All shares',
    'MOEX',
    'Taiwan Weighted',
    'S&P/TSX',
    'OMXS30',
    'NASDAQ',
    'CAC 40',
    'NIFTY 50',
    # 'BKA',
    'Budapest SE',
    'BIST 100',
    'DFM General',
    'Tadawul All Share',
    'Oslo All Share',
    'TA 35',
    'BET',
    'AEX',
    'DSE 30',
    'Amman SE AllShare',
    'ATX',
    'ICEX Main',
    'Blue-Chip SBITOP',
    'PX',
    'KASE',
    'LSE All Share',
    'BSE SOFIX',
    'VN 30',
    'BLOM Stock',
    'Costa Rica Indice Accionario',
    'S&P MERVAL',
    'CSE All-Share',
    'MNE TOP 20',
    # 'ZSE All Share',
]

# https://en.wikipedia.org/wiki/ISO_4217
# https://www.iban.com/currency-codes
currency_countries = ['',
'AFGHANISTAN',
'ALBANIA',
'ALGERIA',
'AMERICAN SAMOA',
'ANDORRA',
'ANGOLA',
'ANGUILLA',
'ANTARCTICA',
'ANTIGUA AND BARBUDA',
'ARGENTINA',
'ARMENIA',
'ARUBA',
'AUSTRALIA',
'AUSTRIA',
'AZERBAIJAN',
'BAHAMAS',
'BAHRAIN',
'BANGLADESH',
'BARBADOS',
'BELARUS',
'BELGIUM',
'BELIZE',
'BENIN',
'BERMUDA',
'BHUTAN',
'BHUTAN',
'BOLIVIA',
'BONAIRE, SINT EUSTATIUS AND SABA',
'BOSNIA AND HERZEGOVINA',
'BOTSWANA',
'BOUVET ISLAND',
'BRAZIL',
'BRITISH INDIAN OCEAN TERRITORY (THE)',
'BRUNEI DARUSSALAM',
'BULGARIA',
'BURKINA FASO',
'BURUNDI',
'CABO VERDE',
'CAMBODIA',
'CAMEROON',
'CANADA',
'CAYMAN ISLANDS',
'CENTRAL AFRICAN REPUBLIC',
'CHAD',
'CHILE',
'CHINA',
'CHRISTMAS ISLAND',
'COCOS ISLANDS',
'COLOMBIA',
'COLOMBIA',
'COMOROS',
'DEMOCRATIC CONGO',
'CONGO',
'COOK ISLANDS',
'COSTA RICA',
'CROATIA',
'CUBA',
'CUBA',
'CURAÇAO',
'CYPRUS',
'CZECH REPUBLIC',
"CÔTE D'IVOIRE",
'DENMARK',
'DJIBOUTI',
'DOMINICA',
'DOMINICAN REPUBLIC',
'ECUADOR',
'EGYPT',
'EL SALVADOR',
'EL SALVADOR',
'EQUATORIAL GUINEA',
'ERITREA',
'ESTONIA',
'ETHIOPIA',
'EUROPEAN UNION',
'FALKLAND ISLANDS',
'FAROE ISLANDS',
'FIJI',
'FINLAND',
'FRANCE',
'FRENCH GUIANA',
'FRENCH POLYNESIA',
'FRENCH SOUTHERN TERRITORIES',
'GABON',
'GAMBIA',
'GEORGIA',
'GERMANY',
'GHANA',
'GIBRALTAR',
'GREECE',
'GREENLAND',
'GRENADA',
'GUADELOUPE',
'GUAM',
'GUATEMALA',
'GUERNSEY',
'GUINEA',
'GUINEA-BISSAU',
'GUYANA',
'HAITI',
'HAITI',
'HEARD ISLAND AND McDONALD ISLANDS',
'HOLY SEE (THE)',
'HONDURAS',
'HONG KONG',
'HUNGARY',
'ICELAND',
'INDIA',
'INDONESIA',
'INTERNATIONAL MONETARY FUND (IMF) ',
'IRAN',
'IRAQ',
'IRELAND',
'ISLE OF MAN',
'ISRAEL',
'ITALY',
'JAMAICA',
'JAPAN',
'JERSEY',
'JORDAN',
'KAZAKHSTAN',
'KENYA',
'KIRIBATI',
'NORTH KOREA',
'SOUTH KOREA',
'KUWAIT',
'KYRGYZSTAN',
'LAOS',
'LATVIA',
'LEBANON',
'LESOTHO',
'LESOTHO',
'LIBERIA',
'LIBYA',
'LIECHTENSTEIN',
'LITHUANIA',
'LUXEMBOURG',
'MACAO',
'MADAGASCAR',
'MALAWI',
'MALAYSIA',
'MALDIVES',
'MALI',
'MALTA',
'MARSHALL ISLANDS',
'MARTINIQUE',
'MAURITANIA',
'MAURITIUS',
'MAYOTTE',
'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP',
'MEXICO',
'MEXICO',
'MICRONESIA',
'MOLDOVA',
'MONACO',
'MONGOLIA',
'MONTENEGRO',
'MONTSERRAT',
'MOROCCO',
'MOZAMBIQUE',
'MYANMAR',
'NAMIBIA',
'NAMIBIA',
'NAURU',
'NEPAL',
'NETHERLANDS',
'NEW CALEDONIA',
'NEW ZEALAND',
'NICARAGUA',
'NIGER',
'NIGERIA',
'NIUE',
'NORFOLK ISLAND',
'NORTHERN MARIANA ISLANDS',
'NORWAY',
'OMAN',
'PAKISTAN',
'PALAU',
'PALESTINE, STATE OF',
'PANAMA',
'PANAMA',
'PAPUA NEW GUINEA',
'PARAGUAY',
'PERU',
'PHILIPPINES',
'PITCAIRN',
'POLAND',
'PORTUGAL',
'PUERTO RICO',
'QATAR',
'REPUBLIC OF NORTH MACEDONIA',
'ROMANIA',
'RUSSIA',
'RWANDA',
'RÉUNION',
'SAINT BARTHÉLEMY',
'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA',
'SAINT KITTS AND NEVIS',
'SAINT LUCIA',
'SAINT MARTIN',
'SAINT PIERRE AND MIQUELON',
'SAINT VINCENT AND THE GRENADINES',
'SAMOA',
'SAN MARINO',
'SAO TOME AND PRINCIPE',
'SAUDI ARABIA',
'SENEGAL',
'SERBIA',
'SEYCHELLES',
'SIERRA LEONE',
'SINGAPORE',
'SINT MAARTEN (DUTCH PART)',
'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"',
'SLOVAKIA',
'SLOVENIA',
'SOLOMON ISLANDS',
'SOMALIA',
'SOUTH AFRICA',
'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
'SOUTH SUDAN',
'SPAIN',
'SRI LANKA',
'SUDAN',
'SURINAME',
'SVALBARD AND JAN MAYEN',
'SWAZILAND',
'SWEDEN',
'SWITZERLAND',
'SYRIAN ARAB REPUBLIC',
'TAIWAN',
'TAJIKISTAN',
'TANZANIA',
'THAILAND',
'TIMOR-LESTE',
'TOGO',
'TOKELAU',
'TONGA',
'TRINIDAD AND TOBAGO',
'TUNISIA',
'TURKEY',
'TURKMENISTAN',
'TURKS AND CAICOS ISLANDS',
'TUVALU',
'UGANDA',
'UKRAINE',
'DUBAI',  # 'UNITED ARAB EMIRATES',
'UNITED KINGDOM',
'UNITED STATES',
'URUGUAY',
'URUGUAY',
'UZBEKISTAN',
'VANUATU',
'VENEZUELA',
'VIETNAM',
'VIRGIN ISLANDS BRITISH',
'VIRGIN ISLANDS US',
'WALLIS AND FUTUNA',
'WESTERN SAHARA',
'YEMEN',
'ZAMBIA',
'ZIMBABWE',
'ÅLAND ISLANDS',
]

# https://en.wikipedia.org/wiki/ISO_4217
# https://www.iban.com/currency-codes
currency_codes = ['',
'AFN',
'ALL',
'DZD',
'USD',
'EUR',
'AOA',
'XCD',
'   ',
'XCD',
'ARS',
'AMD',
'AWG',
'AUD',
'EUR',
'AZN',
'BSD',
'BHD',
'BDT',
'BBD',
'BYN',
'EUR',
'BZD',
'XOF',
'BMD',
'BTN',
'INR',
'BOB',  # 'BOV',
'USD',
'BAM',
'BWP',
'NOK',
'BRL',
'USD',
'BND',
'BGN',
'XOF',
'BIF',
'CVE',
'KHR',
'XAF',
'CAD',
'KYD',
'XAF',
'XAF',
'CLP',  # 'CLF',
'CNY',
'AUD',
'AUD',
'COP',
'COU',
'KMF',
'CDF',
'XAF',
'NZD',
'CRC',
'HRK',
'CUC',
'CUP',
'ANG',
'EUR',
'CZK',
'XOF',
'DKK',
'DJF',
'XCD',
'DOP',
'USD',
'EGP',
'SVC',
'USD',
'XAF',
'ERN',
'EUR',
'ETB',
'EUR',
'FKP',
'DKK',
'FJD',
'EUR',
'EUR',
'EUR',
'XPF',
'EUR',
'XAF',
'GMD',
'GEL',
'EUR',
'GHS',
'GIP',
'EUR',
'DKK',
'XCD',
'EUR',
'USD',
'GTQ',
'GBP',
'GNF',
'XOF',
'GYD',
'HTG',
'USD',
'AUD',
'EUR',
'HNL',
'HKD',
'HUF',
'ISK',
'INR',
'IDR',
'XDR',
'IRR',
'IQD',
'EUR',
'GBP',
'ILS',
'EUR',
'JMD',
'JPY',
'GBP',
'JOD',
'KZT',
'KES',
'AUD',
'KPW',
'KRW',
'KWD',
'KGS',
'LAK',
'EUR',
'LBP',
'LSL',
'ZAR',
'LRD',
'LYD',
'CHF',
'EUR',
'EUR',
'MOP',
'MGA',
'MWK',
'MYR',
'MVR',
'XOF',
'EUR',
'USD',
'EUR',
'MRU',
'MUR',
'EUR',
'XUA',
'MXN',
'MXV',
'USD',
'MDL',
'EUR',
'MNT',
'EUR',
'XCD',
'MAD',
'MZN',
'MMK',
'NAD',
'ZAR',
'AUD',
'NPR',
'EUR',
'XPF',
'NZD',
'NIO',
'XOF',
'NGN',
'NZD',
'AUD',
'USD',
'NOK',
'OMR',
'PKR',
'USD',
'   ',
'PAB',
'USD',
'PGK',
'PYG',
'PEN',
'PHP',
'NZD',
'PLN',
'EUR',
'USD',
'QAR',
'MKD',
'RON',
'RUB',
'RWF',
'EUR',
'EUR',
'SHP',
'XCD',
'XCD',
'EUR',
'EUR',
'XCD',
'WST',
'EUR',
'STN',
'SAR',
'XOF',
'RSD',
'SCR',
'SLL',
'SGD',
'ANG',
'XSU',
'EUR',
'EUR',
'SBD',
'SOS',
'ZAR',
'   ',
'SSP',
'EUR',
'LKR',
'SDG',
'SRD',
'NOK',
'SZL',
'SEK',
'CHF',  # 'CHE', 'CHW',
'SYP',
'TWD',
'TJS',
'TZS',
'THB',
'USD',
'XOF',
'NZD',
'TOP',
'TTD',
'TND',
'TRY',
'TMT',
'USD',
'AUD',
'UGX',
'UAH',
'AED',
'GBP',
'USD',  # 'USN',
'UYI',
'UYU',
'UZS',
'VUV',
'VES',  # 'VEF',
'VND',
'USD',
'USD',
'XPF',
'MAD',
'YER',
'ZMW',
'ZWL',
'EUR',
]

idx_latin_america = [
    'Venezuela',
    'Brazil',
    'Colombia',
    'Peru',
    'Chile',
    'Mexico',
    'Costa Rica',
    'Argentina',
]

def country_adjust_name(country):
    if country.lower() == 'united states 2':
        country = country[0:-2]
    return country

def country_pos(country):
    country = country_adjust_name(country)
    country = country.lower()
    if country in country_names:
        return country_names.index(country)
    else:
        return 0

def country_to_isoa3(country):
    country = country_adjust_name(country)
    return country_isoa3[ country_pos(country) ]

def country_to_currency(country):
    country = country_adjust_name(country)
    country = country.upper()
    if country in currency_countries:
        pos = currency_countries.index(country)
        return currency_codes[pos]
    else:
        return 0


def country_to_portuguese(country):
    if country.lower() not in country_names_en:
        return country
    else:
        pos = country_names_en.index(country.lower())
        return (country_names_pt[pos])


def init_countries():
    global country_names_en, country_names_pt

    df = pd.read_csv('data/config/countries.csv', sep=';')
    country_names_en = df['country'].to_list()
    country_names_pt = df['port'].to_list()

    # Coloca todos os nomes em minúsculas
    i = 0
    for country in idx_country_names:
        idx_country_names[i] = country.lower()
        i += 1
